using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class SaturatedZoneSubCatchment: PFSMapper
  {

    private Subcatchments _sZShallowGWRoutingZones;
    private Subcatchments _sZDeepGWRoutingZones;
    private RiverMF _well;

    internal SaturatedZoneSubCatchment(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "SZShallowGWRoutingZones":
          _sZShallowGWRoutingZones = new Subcatchments(sub);
          break;
        case "SZDeepGWRoutingZones":
          _sZDeepGWRoutingZones = new Subcatchments(sub);
          break;
        case "Well":
          _well = new RiverMF(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public Subcatchments SZShallowGWRoutingZones
    {
     get { return _sZShallowGWRoutingZones; }
    }

    public Subcatchments SZDeepGWRoutingZones
    {
     get { return _sZDeepGWRoutingZones; }
    }

    public RiverMF Well
    {
     get { return _well; }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int Wells
    {
      get
      {
        return _pfsHandle.GetKeyword("Wells", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Wells", 1).GetParameter(1).Value = value;
      }
    }

  }
}
