using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class GeoLayersSZ: PFSMapper
  {

    private Layer_1 _layer_1;
    private Layer_1 _layer_2;
    private Layer_1 _layer_3;
    private Layer_1 _layer_4;
    private Layer_1 _layer_5;
    private Layer_1 _layer_6;
    private Layer_1 _layer_7;
    private Layer_1 _layer_8;
    private Layer_1 _layer_9;
    private Layer_1 _layer_10;
    private Layer_1 _layer_11;
    private Layer_1 _layer_12;
    private Layer_1 _layer_13;
    private Layer_1 _layer_14;
    private Layer_1 _layer_15;
    private Layer_1 _layer_16;
    private Layer_1 _layer_17;
    private Layer_1 _layer_18;
    private Layer_1 _layer_19;
    private Layer_1 _layer_20;
    private Layer_1 _layer_21;
    private Layer_1 _layer_22;
    private Layer_1 _layer_23;
    private Layer_1 _layer_24;
    private Layer_1 _layer_25;
    private Layer_1 _layer_26;
    private Layer_1 _layer_27;
    private Layer_1 _layer_28;
    private Layer_1 _layer_29;
    private Layer_1 _layer_30;
    private Layer_1 _layer_31;
    private Layer_1 _layer_32;
    private Layer_1 _layer_33;
    private Layer_1 _layer_34;
    private Layer_1 _layer_35;
    private Layer_1 _layer_36;
    private Layer_1 _layer_37;
    private Layer_1 _layer_38;
    private Layer_1 _layer_39;
    private Layer_1 _layer_40;
    private Layer_1 _layer_41;
    private Layer_1 _layer_42;
    private Layer_1 _layer_43;
    private Layer_1 _layer_44;
    private Layer_1 _layer_45;
    private Layer_1 _layer_46;
    private Layer_1 _layer_47;

    internal GeoLayersSZ(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "Layer_1":
          _layer_1 = new Layer_1(sub);
          break;
        case "Layer_2":
          _layer_2 = new Layer_1(sub);
          break;
        case "Layer_3":
          _layer_3 = new Layer_1(sub);
          break;
        case "Layer_4":
          _layer_4 = new Layer_1(sub);
          break;
        case "Layer_5":
          _layer_5 = new Layer_1(sub);
          break;
        case "Layer_6":
          _layer_6 = new Layer_1(sub);
          break;
        case "Layer_7":
          _layer_7 = new Layer_1(sub);
          break;
        case "Layer_8":
          _layer_8 = new Layer_1(sub);
          break;
        case "Layer_9":
          _layer_9 = new Layer_1(sub);
          break;
        case "Layer_10":
          _layer_10 = new Layer_1(sub);
          break;
        case "Layer_11":
          _layer_11 = new Layer_1(sub);
          break;
        case "Layer_12":
          _layer_12 = new Layer_1(sub);
          break;
        case "Layer_13":
          _layer_13 = new Layer_1(sub);
          break;
        case "Layer_14":
          _layer_14 = new Layer_1(sub);
          break;
        case "Layer_15":
          _layer_15 = new Layer_1(sub);
          break;
        case "Layer_16":
          _layer_16 = new Layer_1(sub);
          break;
        case "Layer_17":
          _layer_17 = new Layer_1(sub);
          break;
        case "Layer_18":
          _layer_18 = new Layer_1(sub);
          break;
        case "Layer_19":
          _layer_19 = new Layer_1(sub);
          break;
        case "Layer_20":
          _layer_20 = new Layer_1(sub);
          break;
        case "Layer_21":
          _layer_21 = new Layer_1(sub);
          break;
        case "Layer_22":
          _layer_22 = new Layer_1(sub);
          break;
        case "Layer_23":
          _layer_23 = new Layer_1(sub);
          break;
        case "Layer_24":
          _layer_24 = new Layer_1(sub);
          break;
        case "Layer_25":
          _layer_25 = new Layer_1(sub);
          break;
        case "Layer_26":
          _layer_26 = new Layer_1(sub);
          break;
        case "Layer_27":
          _layer_27 = new Layer_1(sub);
          break;
        case "Layer_28":
          _layer_28 = new Layer_1(sub);
          break;
        case "Layer_29":
          _layer_29 = new Layer_1(sub);
          break;
        case "Layer_30":
          _layer_30 = new Layer_1(sub);
          break;
        case "Layer_31":
          _layer_31 = new Layer_1(sub);
          break;
        case "Layer_32":
          _layer_32 = new Layer_1(sub);
          break;
        case "Layer_33":
          _layer_33 = new Layer_1(sub);
          break;
        case "Layer_34":
          _layer_34 = new Layer_1(sub);
          break;
        case "Layer_35":
          _layer_35 = new Layer_1(sub);
          break;
        case "Layer_36":
          _layer_36 = new Layer_1(sub);
          break;
        case "Layer_37":
          _layer_37 = new Layer_1(sub);
          break;
        case "Layer_38":
          _layer_38 = new Layer_1(sub);
          break;
        case "Layer_39":
          _layer_39 = new Layer_1(sub);
          break;
        case "Layer_40":
          _layer_40 = new Layer_1(sub);
          break;
        case "Layer_41":
          _layer_41 = new Layer_1(sub);
          break;
        case "Layer_42":
          _layer_42 = new Layer_1(sub);
          break;
        case "Layer_43":
          _layer_43 = new Layer_1(sub);
          break;
        case "Layer_44":
          _layer_44 = new Layer_1(sub);
          break;
        case "Layer_45":
          _layer_45 = new Layer_1(sub);
          break;
        case "Layer_46":
          _layer_46 = new Layer_1(sub);
          break;
        case "Layer_47":
          _layer_47 = new Layer_1(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public Layer_1 Layer_1
    {
     get { return _layer_1; }
    }

    public Layer_1 Layer_2
    {
     get { return _layer_2; }
    }

    public Layer_1 Layer_3
    {
     get { return _layer_3; }
    }

    public Layer_1 Layer_4
    {
     get { return _layer_4; }
    }

    public Layer_1 Layer_5
    {
     get { return _layer_5; }
    }

    public Layer_1 Layer_6
    {
     get { return _layer_6; }
    }

    public Layer_1 Layer_7
    {
     get { return _layer_7; }
    }

    public Layer_1 Layer_8
    {
     get { return _layer_8; }
    }

    public Layer_1 Layer_9
    {
     get { return _layer_9; }
    }

    public Layer_1 Layer_10
    {
     get { return _layer_10; }
    }

    public Layer_1 Layer_11
    {
     get { return _layer_11; }
    }

    public Layer_1 Layer_12
    {
     get { return _layer_12; }
    }

    public Layer_1 Layer_13
    {
     get { return _layer_13; }
    }

    public Layer_1 Layer_14
    {
     get { return _layer_14; }
    }

    public Layer_1 Layer_15
    {
     get { return _layer_15; }
    }

    public Layer_1 Layer_16
    {
     get { return _layer_16; }
    }

    public Layer_1 Layer_17
    {
     get { return _layer_17; }
    }

    public Layer_1 Layer_18
    {
     get { return _layer_18; }
    }

    public Layer_1 Layer_19
    {
     get { return _layer_19; }
    }

    public Layer_1 Layer_20
    {
     get { return _layer_20; }
    }

    public Layer_1 Layer_21
    {
     get { return _layer_21; }
    }

    public Layer_1 Layer_22
    {
     get { return _layer_22; }
    }

    public Layer_1 Layer_23
    {
     get { return _layer_23; }
    }

    public Layer_1 Layer_24
    {
     get { return _layer_24; }
    }

    public Layer_1 Layer_25
    {
     get { return _layer_25; }
    }

    public Layer_1 Layer_26
    {
     get { return _layer_26; }
    }

    public Layer_1 Layer_27
    {
     get { return _layer_27; }
    }

    public Layer_1 Layer_28
    {
     get { return _layer_28; }
    }

    public Layer_1 Layer_29
    {
     get { return _layer_29; }
    }

    public Layer_1 Layer_30
    {
     get { return _layer_30; }
    }

    public Layer_1 Layer_31
    {
     get { return _layer_31; }
    }

    public Layer_1 Layer_32
    {
     get { return _layer_32; }
    }

    public Layer_1 Layer_33
    {
     get { return _layer_33; }
    }

    public Layer_1 Layer_34
    {
     get { return _layer_34; }
    }

    public Layer_1 Layer_35
    {
     get { return _layer_35; }
    }

    public Layer_1 Layer_36
    {
     get { return _layer_36; }
    }

    public Layer_1 Layer_37
    {
     get { return _layer_37; }
    }

    public Layer_1 Layer_38
    {
     get { return _layer_38; }
    }

    public Layer_1 Layer_39
    {
     get { return _layer_39; }
    }

    public Layer_1 Layer_40
    {
     get { return _layer_40; }
    }

    public Layer_1 Layer_41
    {
     get { return _layer_41; }
    }

    public Layer_1 Layer_42
    {
     get { return _layer_42; }
    }

    public Layer_1 Layer_43
    {
     get { return _layer_43; }
    }

    public Layer_1 Layer_44
    {
     get { return _layer_44; }
    }

    public Layer_1 Layer_45
    {
     get { return _layer_45; }
    }

    public Layer_1 Layer_46
    {
     get { return _layer_46; }
    }

    public Layer_1 Layer_47
    {
     get { return _layer_47; }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int MzSEPfsListItemCount
    {
      get
      {
        return _pfsHandle.GetKeyword("MzSEPfsListItemCount", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MzSEPfsListItemCount", 1).GetParameter(1).Value = value;
      }
    }

    public int NumberOfLayers
    {
      get
      {
        return _pfsHandle.GetKeyword("NumberOfLayers", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("NumberOfLayers", 1).GetParameter(1).Value = value;
      }
    }

  }
}
