using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class Item_1: PFSMapper
  {


    internal Item_1(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int DELT
    {
      get
      {
        return _pfsHandle.GetKeyword("DELT", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("DELT", 1).GetParameter(1).Value = value;
      }
    }

    public int TMIN
    {
      get
      {
        return _pfsHandle.GetKeyword("TMIN", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("TMIN", 1).GetParameter(1).Value = value;
      }
    }

    public int TMAX
    {
      get
      {
        return _pfsHandle.GetKeyword("TMAX", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("TMAX", 1).GetParameter(1).Value = value;
      }
    }

    public int TSMULT
    {
      get
      {
        return _pfsHandle.GetKeyword("TSMULT", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("TSMULT", 1).GetParameter(1).Value = value;
      }
    }

    public int TSDIV
    {
      get
      {
        return _pfsHandle.GetKeyword("TSDIV", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("TSDIV", 1).GetParameter(1).Value = value;
      }
    }

    public int NSTP
    {
      get
      {
        return _pfsHandle.GetKeyword("NSTP", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("NSTP", 1).GetParameter(1).Value = value;
      }
    }

    public int SSTR
    {
      get
      {
        return _pfsHandle.GetKeyword("SSTR", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("SSTR", 1).GetParameter(1).Value = value;
      }
    }

  }
}
