using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class CommandArea: PFSMapper
  {

    private Topography _iNDIRECT_APPLICATION_AREA;
    private Sources _sources;

    internal CommandArea(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "INDIRECT_APPLICATION_AREA":
          _iNDIRECT_APPLICATION_AREA = new Topography(sub);
          break;
        case "Sources":
          _sources = new Sources(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public Topography INDIRECT_APPLICATION_AREA
    {
     get { return _iNDIRECT_APPLICATION_AREA; }
    }

    public Sources Sources
    {
     get { return _sources; }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public string AreaName
    {
      get
      {
        return _pfsHandle.GetKeyword("AreaName", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("AreaName", 1).GetParameter(1).Value = value;
      }
    }

    public string AreaCodeID
    {
      get
      {
        return _pfsHandle.GetKeyword("AreaCodeID", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("AreaCodeID", 1).GetParameter(1).Value = value;
      }
    }

    public int AreaCode
    {
      get
      {
        return _pfsHandle.GetKeyword("AreaCode", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("AreaCode", 1).GetParameter(1).Value = value;
      }
    }

  }
}
