using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class CompControlParaOL: PFSMapper
  {


    internal CompControlParaOL(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int SolverOption
    {
      get
      {
        return _pfsHandle.GetKeyword("SolverOption", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("SolverOption", 1).GetParameter(1).Value = value;
      }
    }

    public int MaxNoOfIter
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxNoOfIter", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxNoOfIter", 1).GetParameter(1).Value = value;
      }
    }

    public double MaxHeadChange
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxHeadChange", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxHeadChange", 1).GetParameter(1).Value = value;
      }
    }

    public double MaxResidualError
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxResidualError", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxResidualError", 1).GetParameter(1).Value = value;
      }
    }

    public double RelaxFactor
    {
      get
      {
        return _pfsHandle.GetKeyword("RelaxFactor", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("RelaxFactor", 1).GetParameter(1).Value = value;
      }
    }

    public double MaxCourant_Explicit
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxCourant_Explicit", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxCourant_Explicit", 1).GetParameter(1).Value = value;
      }
    }

    public double WaterDepthThreshold
    {
      get
      {
        return _pfsHandle.GetKeyword("WaterDepthThreshold", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("WaterDepthThreshold", 1).GetParameter(1).Value = value;
      }
    }

    public double OLFlowReductionGradientThreshold
    {
      get
      {
        return _pfsHandle.GetKeyword("OLFlowReductionGradientThreshold", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("OLFlowReductionGradientThreshold", 1).GetParameter(1).Value = value;
      }
    }

    public int OLRiverExchangeOption
    {
      get
      {
        return _pfsHandle.GetKeyword("OLRiverExchangeOption", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("OLRiverExchangeOption", 1).GetParameter(1).Value = value;
      }
    }

    public double WeirFlowReductionDepthThreshold
    {
      get
      {
        return _pfsHandle.GetKeyword("WeirFlowReductionDepthThreshold", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("WeirFlowReductionDepthThreshold", 1).GetParameter(1).Value = value;
      }
    }

  }
}
