using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class Demand: PFSMapper
  {

    private DFS_2D_DATA_FILE _tIME_SERIES_FILE_1;
    private DFS_2D_DATA_FILE _tIME_SERIES_FILE_2;
    private DFS_2D_DATA_FILE _tIME_SERIES_FILE_3;
    private DFS_2D_DATA_FILE _tIME_SERIES_FILE_4;
    private DFS_2D_DATA_FILE _tIME_SERIES_FILE_5;

    internal Demand(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "TIME_SERIES_FILE_1":
          _tIME_SERIES_FILE_1 = new DFS_2D_DATA_FILE(sub);
          break;
        case "TIME_SERIES_FILE_2":
          _tIME_SERIES_FILE_2 = new DFS_2D_DATA_FILE(sub);
          break;
        case "TIME_SERIES_FILE_3":
          _tIME_SERIES_FILE_3 = new DFS_2D_DATA_FILE(sub);
          break;
        case "TIME_SERIES_FILE_4":
          _tIME_SERIES_FILE_4 = new DFS_2D_DATA_FILE(sub);
          break;
        case "TIME_SERIES_FILE_5":
          _tIME_SERIES_FILE_5 = new DFS_2D_DATA_FILE(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public DFS_2D_DATA_FILE TIME_SERIES_FILE_1
    {
     get { return _tIME_SERIES_FILE_1; }
    }

    public DFS_2D_DATA_FILE TIME_SERIES_FILE_2
    {
     get { return _tIME_SERIES_FILE_2; }
    }

    public DFS_2D_DATA_FILE TIME_SERIES_FILE_3
    {
     get { return _tIME_SERIES_FILE_3; }
    }

    public DFS_2D_DATA_FILE TIME_SERIES_FILE_4
    {
     get { return _tIME_SERIES_FILE_4; }
    }

    public DFS_2D_DATA_FILE TIME_SERIES_FILE_5
    {
     get { return _tIME_SERIES_FILE_5; }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public string DemandName
    {
      get
      {
        return _pfsHandle.GetKeyword("DemandName", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("DemandName", 1).GetParameter(1).Value = value;
      }
    }

    public string DemandCodeID
    {
      get
      {
        return _pfsHandle.GetKeyword("DemandCodeID", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("DemandCodeID", 1).GetParameter(1).Value = value;
      }
    }

    public int DemandCode
    {
      get
      {
        return _pfsHandle.GetKeyword("DemandCode", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("DemandCode", 1).GetParameter(1).Value = value;
      }
    }

    public int DemandType
    {
      get
      {
        return _pfsHandle.GetKeyword("DemandType", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("DemandType", 1).GetParameter(1).Value = value;
      }
    }

    public int DemandReferenceMoistureContent
    {
      get
      {
        return _pfsHandle.GetKeyword("DemandReferenceMoistureContent", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("DemandReferenceMoistureContent", 1).GetParameter(1).Value = value;
      }
    }

    public int TYPE
    {
      get
      {
        return _pfsHandle.GetKeyword("TYPE", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("TYPE", 1).GetParameter(1).Value = value;
      }
    }

    public double DemandMoistureDeficitStartConst
    {
      get
      {
        return _pfsHandle.GetKeyword("DemandMoistureDeficitStartConst", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("DemandMoistureDeficitStartConst", 1).GetParameter(1).Value = value;
      }
    }

    public double DemandMoistureDeficitEndConst
    {
      get
      {
        return _pfsHandle.GetKeyword("DemandMoistureDeficitEndConst", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("DemandMoistureDeficitEndConst", 1).GetParameter(1).Value = value;
      }
    }

    public int DemandConstValue
    {
      get
      {
        return _pfsHandle.GetKeyword("DemandConstValue", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("DemandConstValue", 1).GetParameter(1).Value = value;
      }
    }

    public int CropStressFactorConstValue
    {
      get
      {
        return _pfsHandle.GetKeyword("CropStressFactorConstValue", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("CropStressFactorConstValue", 1).GetParameter(1).Value = value;
      }
    }

    public int PondingDepthConstValue
    {
      get
      {
        return _pfsHandle.GetKeyword("PondingDepthConstValue", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("PondingDepthConstValue", 1).GetParameter(1).Value = value;
      }
    }

  }
}
