using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class WQTSC: PFSMapper
  {


    internal WQTSC(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int MaxSimTimeStepSZ
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxSimTimeStepSZ", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxSimTimeStepSZ", 1).GetParameter(1).Value = value;
      }
    }

    public int MaxSimTimeStepUZ
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxSimTimeStepUZ", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxSimTimeStepUZ", 1).GetParameter(1).Value = value;
      }
    }

    public int MaxSimTimeStepOL
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxSimTimeStepOL", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxSimTimeStepOL", 1).GetParameter(1).Value = value;
      }
    }

    public double MaxAdvectiveCourantSZ
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxAdvectiveCourantSZ", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxAdvectiveCourantSZ", 1).GetParameter(1).Value = value;
      }
    }

    public double MaxAdvectiveCourantUZ
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxAdvectiveCourantUZ", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxAdvectiveCourantUZ", 1).GetParameter(1).Value = value;
      }
    }

    public double MaxAdvectiveCourantOL
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxAdvectiveCourantOL", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxAdvectiveCourantOL", 1).GetParameter(1).Value = value;
      }
    }

    public double MaxDispersiveCourantSZ
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxDispersiveCourantSZ", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxDispersiveCourantSZ", 1).GetParameter(1).Value = value;
      }
    }

    public double MaxDispersiveCourantUZ
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxDispersiveCourantUZ", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxDispersiveCourantUZ", 1).GetParameter(1).Value = value;
      }
    }

    public double MaxDispersiveCourantOL
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxDispersiveCourantOL", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxDispersiveCourantOL", 1).GetParameter(1).Value = value;
      }
    }

    public double MaxTransLimitSZ
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxTransLimitSZ", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxTransLimitSZ", 1).GetParameter(1).Value = value;
      }
    }

    public double MaxTransLimitUZ
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxTransLimitUZ", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxTransLimitUZ", 1).GetParameter(1).Value = value;
      }
    }

    public double MaxTransLimitOL
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxTransLimitOL", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxTransLimitOL", 1).GetParameter(1).Value = value;
      }
    }

    public double MaxCourantMP
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxCourantMP", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxCourantMP", 1).GetParameter(1).Value = value;
      }
    }

  }
}
