//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace MikeSheWrapper.InputDataPreparation {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("OutputTables")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class OutputTables : global::System.Data.DataSet {
        
        private PejlingerOutputDataTable tablePejlingerOutput;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public OutputTables() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected OutputTables(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["PejlingerOutput"] != null)) {
                    base.Tables.Add(new PejlingerOutputDataTable(ds.Tables["PejlingerOutput"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public PejlingerOutputDataTable PejlingerOutput {
            get {
                return this.tablePejlingerOutput;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            OutputTables cln = ((OutputTables)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["PejlingerOutput"] != null)) {
                    base.Tables.Add(new PejlingerOutputDataTable(ds.Tables["PejlingerOutput"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tablePejlingerOutput = ((PejlingerOutputDataTable)(base.Tables["PejlingerOutput"]));
            if ((initTable == true)) {
                if ((this.tablePejlingerOutput != null)) {
                    this.tablePejlingerOutput.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "OutputTables";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/NovanaTables.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablePejlingerOutput = new PejlingerOutputDataTable();
            base.Tables.Add(this.tablePejlingerOutput);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializePejlingerOutput() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            OutputTables ds = new OutputTables();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void PejlingerOutputRowChangeEventHandler(object sender, PejlingerOutputRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class PejlingerOutputDataTable : global::System.Data.TypedTableBase<PejlingerOutputRow> {
            
            private global::System.Data.DataColumn columnNOVANAID;
            
            private global::System.Data.DataColumn columnXUTM;
            
            private global::System.Data.DataColumn columnYUTM;
            
            private global::System.Data.DataColumn columnJUPKOTE;
            
            private global::System.Data.DataColumn columnLOCATION;
            
            private global::System.Data.DataColumn columnNUMBEROFOB;
            
            private global::System.Data.DataColumn columnINTAKETOP;
            
            private global::System.Data.DataColumn columnINTAKEBOT;
            
            private global::System.Data.DataColumn columnSTARTDATO;
            
            private global::System.Data.DataColumn columnENDDATO;
            
            private global::System.Data.DataColumn columnMEANOBS;
            
            private global::System.Data.DataColumn columnMINOBS;
            
            private global::System.Data.DataColumn columnMAXOBS;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PejlingerOutputDataTable() {
                this.TableName = "PejlingerOutput";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal PejlingerOutputDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected PejlingerOutputDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NOVANAIDColumn {
                get {
                    return this.columnNOVANAID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn XUTMColumn {
                get {
                    return this.columnXUTM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn YUTMColumn {
                get {
                    return this.columnYUTM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn JUPKOTEColumn {
                get {
                    return this.columnJUPKOTE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn LOCATIONColumn {
                get {
                    return this.columnLOCATION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NUMBEROFOBColumn {
                get {
                    return this.columnNUMBEROFOB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn INTAKETOPColumn {
                get {
                    return this.columnINTAKETOP;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn INTAKEBOTColumn {
                get {
                    return this.columnINTAKEBOT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn STARTDATOColumn {
                get {
                    return this.columnSTARTDATO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ENDDATOColumn {
                get {
                    return this.columnENDDATO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MEANOBSColumn {
                get {
                    return this.columnMEANOBS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MINOBSColumn {
                get {
                    return this.columnMINOBS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MAXOBSColumn {
                get {
                    return this.columnMAXOBS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PejlingerOutputRow this[int index] {
                get {
                    return ((PejlingerOutputRow)(this.Rows[index]));
                }
            }
            
            public event PejlingerOutputRowChangeEventHandler PejlingerOutputRowChanging;
            
            public event PejlingerOutputRowChangeEventHandler PejlingerOutputRowChanged;
            
            public event PejlingerOutputRowChangeEventHandler PejlingerOutputRowDeleting;
            
            public event PejlingerOutputRowChangeEventHandler PejlingerOutputRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddPejlingerOutputRow(PejlingerOutputRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PejlingerOutputRow AddPejlingerOutputRow(string NOVANAID, double XUTM, double YUTM, double JUPKOTE, string LOCATION, int NUMBEROFOB, double INTAKETOP, double INTAKEBOT, System.DateTime STARTDATO, System.DateTime ENDDATO, double MEANOBS, double MINOBS, double MAXOBS) {
                PejlingerOutputRow rowPejlingerOutputRow = ((PejlingerOutputRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        NOVANAID,
                        XUTM,
                        YUTM,
                        JUPKOTE,
                        LOCATION,
                        NUMBEROFOB,
                        INTAKETOP,
                        INTAKEBOT,
                        STARTDATO,
                        ENDDATO,
                        MEANOBS,
                        MINOBS,
                        MAXOBS};
                rowPejlingerOutputRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowPejlingerOutputRow);
                return rowPejlingerOutputRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                PejlingerOutputDataTable cln = ((PejlingerOutputDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new PejlingerOutputDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnNOVANAID = base.Columns["NOVANAID"];
                this.columnXUTM = base.Columns["XUTM"];
                this.columnYUTM = base.Columns["YUTM"];
                this.columnJUPKOTE = base.Columns["JUPKOTE"];
                this.columnLOCATION = base.Columns["LOCATION"];
                this.columnNUMBEROFOB = base.Columns["NUMBEROFOB"];
                this.columnINTAKETOP = base.Columns["INTAKETOP"];
                this.columnINTAKEBOT = base.Columns["INTAKEBOT"];
                this.columnSTARTDATO = base.Columns["STARTDATO"];
                this.columnENDDATO = base.Columns["ENDDATO"];
                this.columnMEANOBS = base.Columns["MEANOBS"];
                this.columnMINOBS = base.Columns["MINOBS"];
                this.columnMAXOBS = base.Columns["MAXOBS"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnNOVANAID = new global::System.Data.DataColumn("NOVANAID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNOVANAID);
                this.columnXUTM = new global::System.Data.DataColumn("XUTM", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnXUTM);
                this.columnYUTM = new global::System.Data.DataColumn("YUTM", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnYUTM);
                this.columnJUPKOTE = new global::System.Data.DataColumn("JUPKOTE", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJUPKOTE);
                this.columnLOCATION = new global::System.Data.DataColumn("LOCATION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLOCATION);
                this.columnNUMBEROFOB = new global::System.Data.DataColumn("NUMBEROFOB", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNUMBEROFOB);
                this.columnINTAKETOP = new global::System.Data.DataColumn("INTAKETOP", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINTAKETOP);
                this.columnINTAKEBOT = new global::System.Data.DataColumn("INTAKEBOT", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINTAKEBOT);
                this.columnSTARTDATO = new global::System.Data.DataColumn("STARTDATO", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTARTDATO);
                this.columnENDDATO = new global::System.Data.DataColumn("ENDDATO", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnENDDATO);
                this.columnMEANOBS = new global::System.Data.DataColumn("MEANOBS", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMEANOBS);
                this.columnMINOBS = new global::System.Data.DataColumn("MINOBS", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMINOBS);
                this.columnMAXOBS = new global::System.Data.DataColumn("MAXOBS", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMAXOBS);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PejlingerOutputRow NewPejlingerOutputRow() {
                return ((PejlingerOutputRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new PejlingerOutputRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(PejlingerOutputRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.PejlingerOutputRowChanged != null)) {
                    this.PejlingerOutputRowChanged(this, new PejlingerOutputRowChangeEvent(((PejlingerOutputRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.PejlingerOutputRowChanging != null)) {
                    this.PejlingerOutputRowChanging(this, new PejlingerOutputRowChangeEvent(((PejlingerOutputRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.PejlingerOutputRowDeleted != null)) {
                    this.PejlingerOutputRowDeleted(this, new PejlingerOutputRowChangeEvent(((PejlingerOutputRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.PejlingerOutputRowDeleting != null)) {
                    this.PejlingerOutputRowDeleting(this, new PejlingerOutputRowChangeEvent(((PejlingerOutputRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovePejlingerOutputRow(PejlingerOutputRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                OutputTables ds = new OutputTables();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "PejlingerOutputDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class PejlingerOutputRow : global::System.Data.DataRow {
            
            private PejlingerOutputDataTable tablePejlingerOutput;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal PejlingerOutputRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablePejlingerOutput = ((PejlingerOutputDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NOVANAID {
                get {
                    try {
                        return ((string)(this[this.tablePejlingerOutput.NOVANAIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NOVANAID\' in table \'PejlingerOutput\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePejlingerOutput.NOVANAIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double XUTM {
                get {
                    try {
                        return ((double)(this[this.tablePejlingerOutput.XUTMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'XUTM\' in table \'PejlingerOutput\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePejlingerOutput.XUTMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double YUTM {
                get {
                    try {
                        return ((double)(this[this.tablePejlingerOutput.YUTMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'YUTM\' in table \'PejlingerOutput\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePejlingerOutput.YUTMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double JUPKOTE {
                get {
                    try {
                        return ((double)(this[this.tablePejlingerOutput.JUPKOTEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JUPKOTE\' in table \'PejlingerOutput\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePejlingerOutput.JUPKOTEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string LOCATION {
                get {
                    try {
                        return ((string)(this[this.tablePejlingerOutput.LOCATIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LOCATION\' in table \'PejlingerOutput\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePejlingerOutput.LOCATIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int NUMBEROFOB {
                get {
                    try {
                        return ((int)(this[this.tablePejlingerOutput.NUMBEROFOBColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NUMBEROFOB\' in table \'PejlingerOutput\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePejlingerOutput.NUMBEROFOBColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double INTAKETOP {
                get {
                    try {
                        return ((double)(this[this.tablePejlingerOutput.INTAKETOPColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'INTAKETOP\' in table \'PejlingerOutput\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePejlingerOutput.INTAKETOPColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double INTAKEBOT {
                get {
                    try {
                        return ((double)(this[this.tablePejlingerOutput.INTAKEBOTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'INTAKEBOT\' in table \'PejlingerOutput\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePejlingerOutput.INTAKEBOTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime STARTDATO {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablePejlingerOutput.STARTDATOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'STARTDATO\' in table \'PejlingerOutput\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePejlingerOutput.STARTDATOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime ENDDATO {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablePejlingerOutput.ENDDATOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ENDDATO\' in table \'PejlingerOutput\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePejlingerOutput.ENDDATOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double MEANOBS {
                get {
                    try {
                        return ((double)(this[this.tablePejlingerOutput.MEANOBSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MEANOBS\' in table \'PejlingerOutput\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePejlingerOutput.MEANOBSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double MINOBS {
                get {
                    try {
                        return ((double)(this[this.tablePejlingerOutput.MINOBSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MINOBS\' in table \'PejlingerOutput\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePejlingerOutput.MINOBSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double MAXOBS {
                get {
                    try {
                        return ((double)(this[this.tablePejlingerOutput.MAXOBSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MAXOBS\' in table \'PejlingerOutput\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePejlingerOutput.MAXOBSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNOVANAIDNull() {
                return this.IsNull(this.tablePejlingerOutput.NOVANAIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNOVANAIDNull() {
                this[this.tablePejlingerOutput.NOVANAIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsXUTMNull() {
                return this.IsNull(this.tablePejlingerOutput.XUTMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetXUTMNull() {
                this[this.tablePejlingerOutput.XUTMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsYUTMNull() {
                return this.IsNull(this.tablePejlingerOutput.YUTMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetYUTMNull() {
                this[this.tablePejlingerOutput.YUTMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsJUPKOTENull() {
                return this.IsNull(this.tablePejlingerOutput.JUPKOTEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetJUPKOTENull() {
                this[this.tablePejlingerOutput.JUPKOTEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsLOCATIONNull() {
                return this.IsNull(this.tablePejlingerOutput.LOCATIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetLOCATIONNull() {
                this[this.tablePejlingerOutput.LOCATIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNUMBEROFOBNull() {
                return this.IsNull(this.tablePejlingerOutput.NUMBEROFOBColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNUMBEROFOBNull() {
                this[this.tablePejlingerOutput.NUMBEROFOBColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsINTAKETOPNull() {
                return this.IsNull(this.tablePejlingerOutput.INTAKETOPColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetINTAKETOPNull() {
                this[this.tablePejlingerOutput.INTAKETOPColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsINTAKEBOTNull() {
                return this.IsNull(this.tablePejlingerOutput.INTAKEBOTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetINTAKEBOTNull() {
                this[this.tablePejlingerOutput.INTAKEBOTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSTARTDATONull() {
                return this.IsNull(this.tablePejlingerOutput.STARTDATOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSTARTDATONull() {
                this[this.tablePejlingerOutput.STARTDATOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsENDDATONull() {
                return this.IsNull(this.tablePejlingerOutput.ENDDATOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetENDDATONull() {
                this[this.tablePejlingerOutput.ENDDATOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMEANOBSNull() {
                return this.IsNull(this.tablePejlingerOutput.MEANOBSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMEANOBSNull() {
                this[this.tablePejlingerOutput.MEANOBSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMINOBSNull() {
                return this.IsNull(this.tablePejlingerOutput.MINOBSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMINOBSNull() {
                this[this.tablePejlingerOutput.MINOBSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMAXOBSNull() {
                return this.IsNull(this.tablePejlingerOutput.MAXOBSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMAXOBSNull() {
                this[this.tablePejlingerOutput.MAXOBSColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class PejlingerOutputRowChangeEvent : global::System.EventArgs {
            
            private PejlingerOutputRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PejlingerOutputRowChangeEvent(PejlingerOutputRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PejlingerOutputRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591