using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class Catchment: PFSMapper
  {

    private DFS_2D_DATA_FILE _dFS_2D_DATA_FILE;
    private SHAPE_FILE _sHAPE_FILE;

    internal Catchment(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "DFS_2D_DATA_FILE":
          _dFS_2D_DATA_FILE = new DFS_2D_DATA_FILE(sub);
          break;
        case "SHAPE_FILE":
          _sHAPE_FILE = new SHAPE_FILE(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public DFS_2D_DATA_FILE DFS_2D_DATA_FILE
    {
     get { return _dFS_2D_DATA_FILE; }
    }

    public SHAPE_FILE SHAPE_FILE
    {
     get { return _sHAPE_FILE; }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int type
    {
      get
      {
        return _pfsHandle.GetKeyword("type", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("type", 1).GetParameter(1).Value = value;
      }
    }

    public int nxShp
    {
      get
      {
        return _pfsHandle.GetKeyword("nxShp", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("nxShp", 1).GetParameter(1).Value = value;
      }
    }

    public int nyShp
    {
      get
      {
        return _pfsHandle.GetKeyword("nyShp", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("nyShp", 1).GetParameter(1).Value = value;
      }
    }

    public int sizeShp
    {
      get
      {
        return _pfsHandle.GetKeyword("sizeShp", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("sizeShp", 1).GetParameter(1).Value = value;
      }
    }

    public int x0Shp
    {
      get
      {
        return _pfsHandle.GetKeyword("x0Shp", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("x0Shp", 1).GetParameter(1).Value = value;
      }
    }

    public int y0Shp
    {
      get
      {
        return _pfsHandle.GetKeyword("y0Shp", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("y0Shp", 1).GetParameter(1).Value = value;
      }
    }

    public int UTMzoneShp
    {
      get
      {
        return _pfsHandle.GetKeyword("UTMzoneShp", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("UTMzoneShp", 1).GetParameter(1).Value = value;
      }
    }

    public int orientShp
    {
      get
      {
        return _pfsHandle.GetKeyword("orientShp", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("orientShp", 1).GetParameter(1).Value = value;
      }
    }

    public int ShapeAxisUnit
    {
      get
      {
        return _pfsHandle.GetKeyword("ShapeAxisUnit", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("ShapeAxisUnit", 1).GetParameter(1).Value = value;
      }
    }

  }
}
