using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class ColloidControlPara: PFSMapper
  {


    internal ColloidControlPara(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public double ConversionFactor
    {
      get
      {
        return _pfsHandle.GetKeyword("ConversionFactor", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("ConversionFactor", 1).GetParameter(1).Value = value;
      }
    }

    public int MaxPrecDepthPerTimeStep
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxPrecDepthPerTimeStep", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxPrecDepthPerTimeStep", 1).GetParameter(1).Value = value;
      }
    }

    public double PrecThresholdRate
    {
      get
      {
        return _pfsHandle.GetKeyword("PrecThresholdRate", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("PrecThresholdRate", 1).GetParameter(1).Value = value;
      }
    }

    public int FractionTransportedParticle
    {
      get
      {
        return _pfsHandle.GetKeyword("FractionTransportedParticle", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("FractionTransportedParticle", 1).GetParameter(1).Value = value;
      }
    }

    public int WaterDepthCorr
    {
      get
      {
        return _pfsHandle.GetKeyword("WaterDepthCorr", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("WaterDepthCorr", 1).GetParameter(1).Value = value;
      }
    }

    public int DetachmentModel
    {
      get
      {
        return _pfsHandle.GetKeyword("DetachmentModel", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("DetachmentModel", 1).GetParameter(1).Value = value;
      }
    }

    public int ErosionModel
    {
      get
      {
        return _pfsHandle.GetKeyword("ErosionModel", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("ErosionModel", 1).GetParameter(1).Value = value;
      }
    }

    public int IncludeSorption
    {
      get
      {
        return _pfsHandle.GetKeyword("IncludeSorption", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IncludeSorption", 1).GetParameter(1).Value = value;
      }
    }

  }
}
