using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class CompControlParaModSIP: PFSMapper
  {


    internal CompControlParaModSIP(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int MXITER
    {
      get
      {
        return _pfsHandle.GetKeyword("MXITER", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MXITER", 1).GetParameter(1).Value = value;
      }
    }

    public int NPARM
    {
      get
      {
        return _pfsHandle.GetKeyword("NPARM", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("NPARM", 1).GetParameter(1).Value = value;
      }
    }

    public int ACCL
    {
      get
      {
        return _pfsHandle.GetKeyword("ACCL", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("ACCL", 1).GetParameter(1).Value = value;
      }
    }

    public double HCLOSE
    {
      get
      {
        return _pfsHandle.GetKeyword("HCLOSE", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("HCLOSE", 1).GetParameter(1).Value = value;
      }
    }

    public int IPRSIP
    {
      get
      {
        return _pfsHandle.GetKeyword("IPRSIP", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IPRSIP", 1).GetParameter(1).Value = value;
      }
    }

    public double WSEED
    {
      get
      {
        return _pfsHandle.GetKeyword("WSEED", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("WSEED", 1).GetParameter(1).Value = value;
      }
    }

    public int SeedOption
    {
      get
      {
        return _pfsHandle.GetKeyword("SeedOption", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("SeedOption", 1).GetParameter(1).Value = value;
      }
    }

    public int IPCALC
    {
      get
      {
        return _pfsHandle.GetKeyword("IPCALC", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IPCALC", 1).GetParameter(1).Value = value;
      }
    }

  }
}
