using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class GeoScene3D: PFSMapper
  {


    internal GeoScene3D(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int VerticalExaggerationFactor
    {
      get
      {
        return _pfsHandle.GetKeyword("VerticalExaggerationFactor", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("VerticalExaggerationFactor", 1).GetParameter(1).Value = value;
      }
    }

    public int LayerType
    {
      get
      {
        return _pfsHandle.GetKeyword("LayerType", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("LayerType", 1).GetParameter(1).Value = value;
      }
    }

    public int ShowLenses
    {
      get
      {
        return _pfsHandle.GetKeyword("ShowLenses", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("ShowLenses", 1).GetParameter(1).Value = value;
      }
    }

    public int UseAllTimeSteps
    {
      get
      {
        return _pfsHandle.GetKeyword("UseAllTimeSteps", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("UseAllTimeSteps", 1).GetParameter(1).Value = value;
      }
    }

    public int ShowEveryTimeStep
    {
      get
      {
        return _pfsHandle.GetKeyword("ShowEveryTimeStep", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("ShowEveryTimeStep", 1).GetParameter(1).Value = value;
      }
    }

    public double Transparency
    {
      get
      {
        return _pfsHandle.GetKeyword("Transparency", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("Transparency", 1).GetParameter(1).Value = value;
      }
    }

  }
}
