using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class GLOBAL1: PFSMapper
  {

    private DFS_2D_DATA_FILE _tIME_SERIES_FILE_1;
    private DFS_2D_DATA_FILE _tIME_SERIES_FILE_2;
    private RechargeLayer _vEG_PROP_FILES;

    internal GLOBAL1(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "TIME_SERIES_FILE_1":
          _tIME_SERIES_FILE_1 = new DFS_2D_DATA_FILE(sub);
          break;
        case "TIME_SERIES_FILE_2":
          _tIME_SERIES_FILE_2 = new DFS_2D_DATA_FILE(sub);
          break;
        case "VEG_PROP_FILES":
          _vEG_PROP_FILES = new RechargeLayer(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public DFS_2D_DATA_FILE TIME_SERIES_FILE_1
    {
     get { return _tIME_SERIES_FILE_1; }
    }

    public DFS_2D_DATA_FILE TIME_SERIES_FILE_2
    {
     get { return _tIME_SERIES_FILE_2; }
    }

    public RechargeLayer VEG_PROP_FILES
    {
     get { return _vEG_PROP_FILES; }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int FIXED_VALUE_LAI
    {
      get
      {
        return _pfsHandle.GetKeyword("FIXED_VALUE_LAI", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("FIXED_VALUE_LAI", 1).GetParameter(1).Value = value;
      }
    }

    public int FIXED_VALUE_RD
    {
      get
      {
        return _pfsHandle.GetKeyword("FIXED_VALUE_RD", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("FIXED_VALUE_RD", 1).GetParameter(1).Value = value;
      }
    }

    public int TYPE
    {
      get
      {
        return _pfsHandle.GetKeyword("TYPE", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("TYPE", 1).GetParameter(1).Value = value;
      }
    }

  }
}
