using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class InternalBoundaryProp: PFSMapper
  {

    private DFS_2D_DATA_FILE _tIME_SERIES_FILE;
    private DFS_2D_DATA_FILE _dFS_2D_DATA_FILE;
    private Topography _leakCoef;
    private Topography _conductance;
    private Bathymetry _riverBottomElevation;

    internal InternalBoundaryProp(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "TIME_SERIES_FILE":
          _tIME_SERIES_FILE = new DFS_2D_DATA_FILE(sub);
          break;
        case "DFS_2D_DATA_FILE":
          _dFS_2D_DATA_FILE = new DFS_2D_DATA_FILE(sub);
          break;
        case "LeakCoef":
          _leakCoef = new Topography(sub);
          break;
        case "Conductance":
          _conductance = new Topography(sub);
          break;
        case "RiverBottomElevation":
          _riverBottomElevation = new Bathymetry(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public DFS_2D_DATA_FILE TIME_SERIES_FILE
    {
     get { return _tIME_SERIES_FILE; }
    }

    public DFS_2D_DATA_FILE DFS_2D_DATA_FILE
    {
     get { return _dFS_2D_DATA_FILE; }
    }

    public Topography LeakCoef
    {
     get { return _leakCoef; }
    }

    public Topography Conductance
    {
     get { return _conductance; }
    }

    public Bathymetry RiverBottomElevation
    {
     get { return _riverBottomElevation; }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int InternalBoundarySecNumber
    {
      get
      {
        return _pfsHandle.GetKeyword("InternalBoundarySecNumber", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("InternalBoundarySecNumber", 1).GetParameter(1).Value = value;
      }
    }

    public string ID
    {
      get
      {
        return _pfsHandle.GetKeyword("ID", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("ID", 1).GetParameter(1).Value = value;
      }
    }

    public string GridCode
    {
      get
      {
        return _pfsHandle.GetKeyword("GridCode", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("GridCode", 1).GetParameter(1).Value = value;
      }
    }

    public int FixedValue
    {
      get
      {
        return _pfsHandle.GetKeyword("FixedValue", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("FixedValue", 1).GetParameter(1).Value = value;
      }
    }

    public int BoundaryType
    {
      get
      {
        return _pfsHandle.GetKeyword("BoundaryType", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("BoundaryType", 1).GetParameter(1).Value = value;
      }
    }

    public int Type
    {
      get
      {
        return _pfsHandle.GetKeyword("Type", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Type", 1).GetParameter(1).Value = value;
      }
    }

    public int HeadControlLeakage
    {
      get
      {
        return _pfsHandle.GetKeyword("HeadControlLeakage", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("HeadControlLeakage", 1).GetParameter(1).Value = value;
      }
    }

  }
}
