using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class ModModelComp: PFSMapper
  {


    internal ModModelComp(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int OL
    {
      get
      {
        return _pfsHandle.GetKeyword("OL", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("OL", 1).GetParameter(1).Value = value;
      }
    }

    public int River
    {
      get
      {
        return _pfsHandle.GetKeyword("River", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("River", 1).GetParameter(1).Value = value;
      }
    }

    public int RiverModelType
    {
      get
      {
        return _pfsHandle.GetKeyword("RiverModelType", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("RiverModelType", 1).GetParameter(1).Value = value;
      }
    }

    public int Recharge
    {
      get
      {
        return _pfsHandle.GetKeyword("Recharge", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Recharge", 1).GetParameter(1).Value = value;
      }
    }

    public int Recharge_ModelType
    {
      get
      {
        return _pfsHandle.GetKeyword("Recharge_ModelType", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Recharge_ModelType", 1).GetParameter(1).Value = value;
      }
    }

    public int Subsurface
    {
      get
      {
        return _pfsHandle.GetKeyword("Subsurface", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Subsurface", 1).GetParameter(1).Value = value;
      }
    }

    public int Subsurface_ModelType
    {
      get
      {
        return _pfsHandle.GetKeyword("Subsurface_ModelType", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Subsurface_ModelType", 1).GetParameter(1).Value = value;
      }
    }

    public int Modflow2000_BCFType
    {
      get
      {
        return _pfsHandle.GetKeyword("Modflow2000_BCFType", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Modflow2000_BCFType", 1).GetParameter(1).Value = value;
      }
    }

    public int ET
    {
      get
      {
        return _pfsHandle.GetKeyword("ET", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("ET", 1).GetParameter(1).Value = value;
      }
    }

  }
}
