using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class OverlayRiver: PFSMapper
  {


    internal OverlayRiver(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int SourceM11NwkType
    {
      get
      {
        return _pfsHandle.GetKeyword("SourceM11NwkType", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("SourceM11NwkType", 1).GetParameter(1).Value = value;
      }
    }

    public string M11NwkFilename_Specified
    {
      get
      {
        return _pfsHandle.GetKeyword("M11NwkFilename_Specified", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("M11NwkFilename_Specified", 1).GetParameter(1).Value = value;
      }
    }

    public int Display
    {
      get
      {
        return _pfsHandle.GetKeyword("Display", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Display", 1).GetParameter(1).Value = value;
      }
    }

  }
}
