using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class OverlayShape: PFSMapper
  {


    internal OverlayShape(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public string Filename
    {
      get
      {
        return _pfsHandle.GetKeyword("Filename", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("Filename", 1).GetParameter(1).Value = value;
      }
    }

    public string ItemDescr
    {
      get
      {
        return _pfsHandle.GetKeyword("ItemDescr", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("ItemDescr", 1).GetParameter(1).Value = value;
      }
    }

    public int ShapeAxisUnit
    {
      get
      {
        return _pfsHandle.GetKeyword("ShapeAxisUnit", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("ShapeAxisUnit", 1).GetParameter(1).Value = value;
      }
    }

    public int PointSize
    {
      get
      {
        return _pfsHandle.GetKeyword("PointSize", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("PointSize", 1).GetParameter(1).Value = value;
      }
    }

    public int PointStyle
    {
      get
      {
        return _pfsHandle.GetKeyword("PointStyle", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("PointStyle", 1).GetParameter(1).Value = value;
      }
    }

    public int PointType
    {
      get
      {
        return _pfsHandle.GetKeyword("PointType", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("PointType", 1).GetParameter(1).Value = value;
      }
    }

    public int PointColorR
    {
      get
      {
        return _pfsHandle.GetKeyword("PointColorR", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("PointColorR", 1).GetParameter(1).Value = value;
      }
    }

    public int PointColorG
    {
      get
      {
        return _pfsHandle.GetKeyword("PointColorG", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("PointColorG", 1).GetParameter(1).Value = value;
      }
    }

    public int PointColorB
    {
      get
      {
        return _pfsHandle.GetKeyword("PointColorB", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("PointColorB", 1).GetParameter(1).Value = value;
      }
    }

    public int PointTextColorR
    {
      get
      {
        return _pfsHandle.GetKeyword("PointTextColorR", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("PointTextColorR", 1).GetParameter(1).Value = value;
      }
    }

    public int PointTextColorG
    {
      get
      {
        return _pfsHandle.GetKeyword("PointTextColorG", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("PointTextColorG", 1).GetParameter(1).Value = value;
      }
    }

    public int PointTextColorB
    {
      get
      {
        return _pfsHandle.GetKeyword("PointTextColorB", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("PointTextColorB", 1).GetParameter(1).Value = value;
      }
    }

    public double LineThickness
    {
      get
      {
        return _pfsHandle.GetKeyword("LineThickness", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("LineThickness", 1).GetParameter(1).Value = value;
      }
    }

    public int LineStyle
    {
      get
      {
        return _pfsHandle.GetKeyword("LineStyle", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("LineStyle", 1).GetParameter(1).Value = value;
      }
    }

    public int PolygonStyle
    {
      get
      {
        return _pfsHandle.GetKeyword("PolygonStyle", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("PolygonStyle", 1).GetParameter(1).Value = value;
      }
    }

    public int LineColorR
    {
      get
      {
        return _pfsHandle.GetKeyword("LineColorR", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("LineColorR", 1).GetParameter(1).Value = value;
      }
    }

    public int LineColorG
    {
      get
      {
        return _pfsHandle.GetKeyword("LineColorG", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("LineColorG", 1).GetParameter(1).Value = value;
      }
    }

    public int LineColorB
    {
      get
      {
        return _pfsHandle.GetKeyword("LineColorB", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("LineColorB", 1).GetParameter(1).Value = value;
      }
    }

    public int LineTextColorR
    {
      get
      {
        return _pfsHandle.GetKeyword("LineTextColorR", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("LineTextColorR", 1).GetParameter(1).Value = value;
      }
    }

    public int LineTextColorG
    {
      get
      {
        return _pfsHandle.GetKeyword("LineTextColorG", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("LineTextColorG", 1).GetParameter(1).Value = value;
      }
    }

    public int LineTextColorB
    {
      get
      {
        return _pfsHandle.GetKeyword("LineTextColorB", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("LineTextColorB", 1).GetParameter(1).Value = value;
      }
    }

    public int LineTextColorOption
    {
      get
      {
        return _pfsHandle.GetKeyword("LineTextColorOption", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("LineTextColorOption", 1).GetParameter(1).Value = value;
      }
    }

    public int ShowLineText
    {
      get
      {
        return _pfsHandle.GetKeyword("ShowLineText", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("ShowLineText", 1).GetParameter(1).Value = value;
      }
    }

    public int PointTextBackground
    {
      get
      {
        return _pfsHandle.GetKeyword("PointTextBackground", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("PointTextBackground", 1).GetParameter(1).Value = value;
      }
    }

    public int LineTextBackground
    {
      get
      {
        return _pfsHandle.GetKeyword("LineTextBackground", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("LineTextBackground", 1).GetParameter(1).Value = value;
      }
    }

    public int PointTextColorOption
    {
      get
      {
        return _pfsHandle.GetKeyword("PointTextColorOption", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("PointTextColorOption", 1).GetParameter(1).Value = value;
      }
    }

    public int ShowPointText
    {
      get
      {
        return _pfsHandle.GetKeyword("ShowPointText", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("ShowPointText", 1).GetParameter(1).Value = value;
      }
    }

    public int Display
    {
      get
      {
        return _pfsHandle.GetKeyword("Display", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Display", 1).GetParameter(1).Value = value;
      }
    }

  }
}
