using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class River: PFSMapper
  {

    private Topography _floodCodes;
    private Bathymetry _bathymetry;

    internal River(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "FloodCodes":
          _floodCodes = new Topography(sub);
          break;
        case "Bathymetry":
          _bathymetry = new Bathymetry(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public Topography FloodCodes
    {
     get { return _floodCodes; }
    }

    public Bathymetry Bathymetry
    {
     get { return _bathymetry; }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public string Filename
    {
      get
      {
        return _pfsHandle.GetKeyword("Filename", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("Filename", 1).GetParameter(1).Value = value;
      }
    }

    public string FilenameWQ
    {
      get
      {
        return _pfsHandle.GetKeyword("FilenameWQ", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("FilenameWQ", 1).GetParameter(1).Value = value;
      }
    }

    public int Bathymetry1
    {
      get
      {
        return _pfsHandle.GetKeyword("Bathymetry", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Bathymetry", 1).GetParameter(1).Value = value;
      }
    }

    public int FloodCodes1
    {
      get
      {
        return _pfsHandle.GetKeyword("FloodCodes", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("FloodCodes", 1).GetParameter(1).Value = value;
      }
    }

  }
}
