using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class UZSoilProfileProp: PFSMapper
  {

    private CUZSoilProfilePropLayerListPfs _cUZSoilProfilePropLayerListPfs;
    private CUZSoilProfilePropDiscrListPfs _cUZSoilProfilePropDiscrListPfs;

    internal UZSoilProfileProp(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "CUZSoilProfilePropLayerListPfs":
          _cUZSoilProfilePropLayerListPfs = new CUZSoilProfilePropLayerListPfs(sub);
          break;
        case "CUZSoilProfilePropDiscrListPfs":
          _cUZSoilProfilePropDiscrListPfs = new CUZSoilProfilePropDiscrListPfs(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public CUZSoilProfilePropLayerListPfs CUZSoilProfilePropLayerListPfs
    {
     get { return _cUZSoilProfilePropLayerListPfs; }
    }

    public CUZSoilProfilePropDiscrListPfs CUZSoilProfilePropDiscrListPfs
    {
     get { return _cUZSoilProfilePropDiscrListPfs; }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int ProfileSecNumber
    {
      get
      {
        return _pfsHandle.GetKeyword("ProfileSecNumber", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("ProfileSecNumber", 1).GetParameter(1).Value = value;
      }
    }

    public string GridCode
    {
      get
      {
        return _pfsHandle.GetKeyword("GridCode", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("GridCode", 1).GetParameter(1).Value = value;
      }
    }

    public string SoilProfile_ID
    {
      get
      {
        return _pfsHandle.GetKeyword("SoilProfile_ID", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("SoilProfile_ID", 1).GetParameter(1).Value = value;
      }
    }

    public double BYP
    {
      get
      {
        return _pfsHandle.GetKeyword("BYP", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("BYP", 1).GetParameter(1).Value = value;
      }
    }

    public double THR1
    {
      get
      {
        return _pfsHandle.GetKeyword("THR1", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("THR1", 1).GetParameter(1).Value = value;
      }
    }

    public double THR2
    {
      get
      {
        return _pfsHandle.GetKeyword("THR2", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("THR2", 1).GetParameter(1).Value = value;
      }
    }

  }
}
