using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class UZSoilProfilePropDiscr1: PFSMapper
  {


    internal UZSoilProfilePropDiscr1(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public double CellHeight
    {
      get
      {
        return _pfsHandle.GetKeyword("CellHeight", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("CellHeight", 1).GetParameter(1).Value = value;
      }
    }

    public int NoCells
    {
      get
      {
        return _pfsHandle.GetKeyword("NoCells", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("NoCells", 1).GetParameter(1).Value = value;
      }
    }

    public int Dispersivity
    {
      get
      {
        return _pfsHandle.GetKeyword("Dispersivity", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Dispersivity", 1).GetParameter(1).Value = value;
      }
    }

  }
}
