using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class VEG_PROP_FILES1: PFSMapper
  {

    private VegNo_11 _vegNo_1;
    private VegNo_2 _vegNo_2;
    private VegNo_3 _vegNo_3;
    private VegNo_4 _vegNo_4;
    private VegNo_5 _vegNo_5;
    private VegNo_6 _vegNo_6;
    private VegNo_7 _vegNo_7;
    private VegNo_8 _vegNo_8;
    private VegNo_9 _vegNo_9;
    private VegNo_10 _vegNo_10;
    private VegNo_111 _vegNo_11;
    private VegNo_12 _vegNo_12;
    private VegNo_13 _vegNo_13;
    private VegNo_14 _vegNo_14;
    private VegNo_15 _vegNo_15;

    internal VEG_PROP_FILES1(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "VegNo_1":
          _vegNo_1 = new VegNo_11(sub);
          break;
        case "VegNo_2":
          _vegNo_2 = new VegNo_2(sub);
          break;
        case "VegNo_3":
          _vegNo_3 = new VegNo_3(sub);
          break;
        case "VegNo_4":
          _vegNo_4 = new VegNo_4(sub);
          break;
        case "VegNo_5":
          _vegNo_5 = new VegNo_5(sub);
          break;
        case "VegNo_6":
          _vegNo_6 = new VegNo_6(sub);
          break;
        case "VegNo_7":
          _vegNo_7 = new VegNo_7(sub);
          break;
        case "VegNo_8":
          _vegNo_8 = new VegNo_8(sub);
          break;
        case "VegNo_9":
          _vegNo_9 = new VegNo_9(sub);
          break;
        case "VegNo_10":
          _vegNo_10 = new VegNo_10(sub);
          break;
        case "VegNo_11":
          _vegNo_11 = new VegNo_111(sub);
          break;
        case "VegNo_12":
          _vegNo_12 = new VegNo_12(sub);
          break;
        case "VegNo_13":
          _vegNo_13 = new VegNo_13(sub);
          break;
        case "VegNo_14":
          _vegNo_14 = new VegNo_14(sub);
          break;
        case "VegNo_15":
          _vegNo_15 = new VegNo_15(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public VegNo_11 VegNo_1
    {
     get { return _vegNo_1; }
    }

    public VegNo_2 VegNo_2
    {
     get { return _vegNo_2; }
    }

    public VegNo_3 VegNo_3
    {
     get { return _vegNo_3; }
    }

    public VegNo_4 VegNo_4
    {
     get { return _vegNo_4; }
    }

    public VegNo_5 VegNo_5
    {
     get { return _vegNo_5; }
    }

    public VegNo_6 VegNo_6
    {
     get { return _vegNo_6; }
    }

    public VegNo_7 VegNo_7
    {
     get { return _vegNo_7; }
    }

    public VegNo_8 VegNo_8
    {
     get { return _vegNo_8; }
    }

    public VegNo_9 VegNo_9
    {
     get { return _vegNo_9; }
    }

    public VegNo_10 VegNo_10
    {
     get { return _vegNo_10; }
    }

    public VegNo_111 VegNo_11
    {
     get { return _vegNo_11; }
    }

    public VegNo_12 VegNo_12
    {
     get { return _vegNo_12; }
    }

    public VegNo_13 VegNo_13
    {
     get { return _vegNo_13; }
    }

    public VegNo_14 VegNo_14
    {
     get { return _vegNo_14; }
    }

    public VegNo_15 VegNo_15
    {
     get { return _vegNo_15; }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int MzSEPfsListItemCount
    {
      get
      {
        return _pfsHandle.GetKeyword("MzSEPfsListItemCount", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MzSEPfsListItemCount", 1).GetParameter(1).Value = value;
      }
    }

  }
}
