using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class GeoUnit_1: PFSMapper
  {


    internal GeoUnit_1(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public string SoilName
    {
      get
      {
        return _pfsHandle.GetKeyword("SoilName", 1).GetParameter(1).ToString();
      }
      set
      {
        _pfsHandle.GetKeyword("SoilName", 1).GetParameter(1).Value = value;
      }
    }

    public int SoilCode
    {
      get
      {
        return _pfsHandle.GetKeyword("SoilCode", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("SoilCode", 1).GetParameter(1).Value = value;
      }
    }

    public double HorConduc
    {
      get
      {
        return _pfsHandle.GetKeyword("HorConduc", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("HorConduc", 1).GetParameter(1).Value = value;
      }
    }

    public double VerConduc
    {
      get
      {
        return _pfsHandle.GetKeyword("VerConduc", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("VerConduc", 1).GetParameter(1).Value = value;
      }
    }

    public double SpecYield
    {
      get
      {
        return _pfsHandle.GetKeyword("SpecYield", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("SpecYield", 1).GetParameter(1).Value = value;
      }
    }

    public double StorageCoef
    {
      get
      {
        return _pfsHandle.GetKeyword("StorageCoef", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("StorageCoef", 1).GetParameter(1).Value = value;
      }
    }

    public double Porosity
    {
      get
      {
        return _pfsHandle.GetKeyword("Porosity", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("Porosity", 1).GetParameter(1).Value = value;
      }
    }

    public double MatrixPorosity
    {
      get
      {
        return _pfsHandle.GetKeyword("MatrixPorosity", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("MatrixPorosity", 1).GetParameter(1).Value = value;
      }
    }

    public int BulkDensity
    {
      get
      {
        return _pfsHandle.GetKeyword("BulkDensity", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("BulkDensity", 1).GetParameter(1).Value = value;
      }
    }

    public int LHH
    {
      get
      {
        return _pfsHandle.GetKeyword("LHH", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("LHH", 1).GetParameter(1).Value = value;
      }
    }

    public int THH
    {
      get
      {
        return _pfsHandle.GetKeyword("THH", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("THH", 1).GetParameter(1).Value = value;
      }
    }

    public int TVH
    {
      get
      {
        return _pfsHandle.GetKeyword("TVH", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("TVH", 1).GetParameter(1).Value = value;
      }
    }

    public int LVV
    {
      get
      {
        return _pfsHandle.GetKeyword("LVV", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("LVV", 1).GetParameter(1).Value = value;
      }
    }

    public int THV
    {
      get
      {
        return _pfsHandle.GetKeyword("THV", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("THV", 1).GetParameter(1).Value = value;
      }
    }

  }
}
