using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class CompControlParaTimeStep: PFSMapper
  {


    internal CompControlParaTimeStep(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int InitialTimeStep
    {
      get
      {
        return _pfsHandle.GetKeyword("InitialTimeStep", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("InitialTimeStep", 1).GetParameter(1).Value = value;
      }
    }

    public int MaxAllowedOLTimeStep
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxAllowedOLTimeStep", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxAllowedOLTimeStep", 1).GetParameter(1).Value = value;
      }
    }

    public int MaxAllowedUZTimeStep
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxAllowedUZTimeStep", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxAllowedUZTimeStep", 1).GetParameter(1).Value = value;
      }
    }

    public int MaxAllowedSZTimeStep
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxAllowedSZTimeStep", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxAllowedSZTimeStep", 1).GetParameter(1).Value = value;
      }
    }

    public double IncrementRate
    {
      get
      {
        return _pfsHandle.GetKeyword("IncrementRate", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("IncrementRate", 1).GetParameter(1).Value = value;
      }
    }

    public int MaxPrecDepthPerTimeStep
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxPrecDepthPerTimeStep", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxPrecDepthPerTimeStep", 1).GetParameter(1).Value = value;
      }
    }

    public int MaxInfiltDepthPerTimeStep
    {
      get
      {
        return _pfsHandle.GetKeyword("MaxInfiltDepthPerTimeStep", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MaxInfiltDepthPerTimeStep", 1).GetParameter(1).Value = value;
      }
    }

    public int PrecThresholdRate
    {
      get
      {
        return _pfsHandle.GetKeyword("PrecThresholdRate", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("PrecThresholdRate", 1).GetParameter(1).Value = value;
      }
    }

  }
}
