using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class UZGroundWaterDepthList: PFSMapper
  {

    private Bathymetry _uZGroundWaterTable;
    private UZGroundWaterDepth1 _uZGroundWaterDepth1;

    internal UZGroundWaterDepthList(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "UZGroundWaterTable":
          _uZGroundWaterTable = new Bathymetry(sub);
          break;
        case "UZGroundWaterDepth1":
          _uZGroundWaterDepth1 = new UZGroundWaterDepth1(sub);
          break;
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public Bathymetry UZGroundWaterTable
    {
     get { return _uZGroundWaterTable; }
    }

    public UZGroundWaterDepth1 UZGroundWaterDepth1
    {
     get { return _uZGroundWaterDepth1; }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int MzSEPfsListItemCount
    {
      get
      {
        return _pfsHandle.GetKeyword("MzSEPfsListItemCount", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MzSEPfsListItemCount", 1).GetParameter(1).Value = value;
      }
    }

    public int NumberOfLayers
    {
      get
      {
        return _pfsHandle.GetKeyword("NumberOfLayers", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("NumberOfLayers", 1).GetParameter(1).Value = value;
      }
    }

    public int GroundWaterTableOption
    {
      get
      {
        return _pfsHandle.GetKeyword("GroundWaterTableOption", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("GroundWaterTableOption", 1).GetParameter(1).Value = value;
      }
    }

  }
}
