using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class AirFlowSimulationParametersMod: PFSMapper
  {


    internal AirFlowSimulationParametersMod(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int DensityWater
    {
      get
      {
        return _pfsHandle.GetKeyword("DensityWater", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("DensityWater", 1).GetParameter(1).Value = value;
      }
    }

    public double DensityAir
    {
      get
      {
        return _pfsHandle.GetKeyword("DensityAir", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("DensityAir", 1).GetParameter(1).Value = value;
      }
    }

    public double ViscosityWater
    {
      get
      {
        return _pfsHandle.GetKeyword("ViscosityWater", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("ViscosityWater", 1).GetParameter(1).Value = value;
      }
    }

    public double ViscosityAir
    {
      get
      {
        return _pfsHandle.GetKeyword("ViscosityAir", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("ViscosityAir", 1).GetParameter(1).Value = value;
      }
    }

    public double CompressibilityWater
    {
      get
      {
        return _pfsHandle.GetKeyword("CompressibilityWater", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("CompressibilityWater", 1).GetParameter(1).Value = value;
      }
    }

    public double CompressibilityAir
    {
      get
      {
        return _pfsHandle.GetKeyword("CompressibilityAir", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("CompressibilityAir", 1).GetParameter(1).Value = value;
      }
    }

    public int StdAtmPressure
    {
      get
      {
        return _pfsHandle.GetKeyword("StdAtmPressure", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("StdAtmPressure", 1).GetParameter(1).Value = value;
      }
    }

    public double GravityAcceleration
    {
      get
      {
        return _pfsHandle.GetKeyword("GravityAcceleration", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("GravityAcceleration", 1).GetParameter(1).Value = value;
      }
    }

    public int TypeAmbientWaterHeadInput
    {
      get
      {
        return _pfsHandle.GetKeyword("TypeAmbientWaterHeadInput", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("TypeAmbientWaterHeadInput", 1).GetParameter(1).Value = value;
      }
    }

  }
}
