using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class CompControlParaModPCG2: PFSMapper
  {


    internal CompControlParaModPCG2(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
          default:
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int MXITER
    {
      get
      {
        return _pfsHandle.GetKeyword("MXITER", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MXITER", 1).GetParameter(1).Value = value;
      }
    }

    public int ITER1
    {
      get
      {
        return _pfsHandle.GetKeyword("ITER1", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("ITER1", 1).GetParameter(1).Value = value;
      }
    }

    public double HCLOSE
    {
      get
      {
        return _pfsHandle.GetKeyword("HCLOSE", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("HCLOSE", 1).GetParameter(1).Value = value;
      }
    }

    public double RCLOSE
    {
      get
      {
        return _pfsHandle.GetKeyword("RCLOSE", 1).GetParameter(1).ToDouble();
      }
      set
      {
        _pfsHandle.GetKeyword("RCLOSE", 1).GetParameter(1).Value = value;
      }
    }

    public int RELAX
    {
      get
      {
        return _pfsHandle.GetKeyword("RELAX", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("RELAX", 1).GetParameter(1).Value = value;
      }
    }

    public int IPRPCG
    {
      get
      {
        return _pfsHandle.GetKeyword("IPRPCG", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IPRPCG", 1).GetParameter(1).Value = value;
      }
    }

    public int MUTPCG
    {
      get
      {
        return _pfsHandle.GetKeyword("MUTPCG", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MUTPCG", 1).GetParameter(1).Value = value;
      }
    }

    public int DAMP
    {
      get
      {
        return _pfsHandle.GetKeyword("DAMP", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("DAMP", 1).GetParameter(1).Value = value;
      }
    }

  }
}
