using System;
using System.Collections.Generic;
using DHI.Generic.MikeZero;

namespace MikeSheWrapper.InputFiles
{
  /// <summary>
  /// This is an autogenerated class. Do not edit. 
  /// If you want to add methods create a new partial class in another file
  /// </summary>
  public partial class DetailedM11TimeseriesOutput: PFSMapper
  {

    private Item_11 _item_2;
    private Item_11 _item_3;
    private Item_11 _item_4;
    private Item_11 _item_5;
    private Item_11 _item_6;
    private Item_11 _item_7;
    private Item_11 _item_8;
    private Item_11 _item_9;
    private Item_11 _item_10;
    private Item_11 _item_12;
    private Item_11 _item_13;
    private Item_11 _item_14;
    private Item_11 _item_15;
    private Item_11 _item_16;
    private Item_11 _item_17;
    private Item_11 _item_18;
    private Item_11 _item_19;
    private Item_11 _item_20;
    private Item_11 _item_21;
    private Item_11 _item_22;
    private Item_11 _item_23;
    private Item_11 _item_24;
    private Item_11 _item_25;
    private Item_11 _item_26;
    private Item_11 _item_27;
    private Item_11 _item_28;
    private Item_11 _item_29;
    private Item_11 _item_30;
    private Item_11 _item_31;
    private Item_11 _item_32;
    private Item_11 _item_33;
    private Item_11 _item_34;
    private Item_11 _item_35;
    private Item_11 _item_36;
    private Item_11 _item_37;
    private Item_11 _item_38;
    private Item_11 _item_39;
    private Item_11 _item_40;
    private Item_11 _item_41;
    private Item_11 _item_42;
    private Item_11 _item_43;
    private Item_11 _item_44;
    private Item_11 _item_45;
    private Item_11 _item_46;
    private Item_11 _item_47;
    private Item_11 _item_48;
    private Item_11 _item_49;
    private Item_11 _item_50;
    private Item_11 _item_51;
    private Item_11 _item_52;
    private Item_11 _item_53;
    private Item_11 _item_54;
    private Item_11 _item_55;
    private Item_11 _item_56;
    private Item_11 _item_57;
    private Item_11 _item_58;
    private Item_11 _item_59;
    private Item_11 _item_60;
    private Item_11 _item_61;
    private Item_11 _item_62;
    private Item_11 _item_63;
    private Item_11 _item_64;
    private Item_11 _item_65;
    private Item_11 _item_66;
    private Item_11 _item_67;
    private Item_11 _item_68;
    private Item_11 _item_69;
    private Item_11 _item_70;
    private Item_11 _item_71;
    private Item_11 _item_72;
    private Item_11 _item_73;
    private Item_11 _item_74;
    private List<Item_11> _item_1s = new List<Item_11>();

    internal DetailedM11TimeseriesOutput(PFSSection Section)
    {
      _pfsHandle = Section;

      for (int i = 1; i <= Section.GetSectionsNo(); i++)
      {
        PFSSection sub = Section.GetSection(i);
        switch (sub.Name)
        {
        case "Item_2":
          _item_2 = new Item_11(sub);
          break;
        case "Item_3":
          _item_3 = new Item_11(sub);
          break;
        case "Item_4":
          _item_4 = new Item_11(sub);
          break;
        case "Item_5":
          _item_5 = new Item_11(sub);
          break;
        case "Item_6":
          _item_6 = new Item_11(sub);
          break;
        case "Item_7":
          _item_7 = new Item_11(sub);
          break;
        case "Item_8":
          _item_8 = new Item_11(sub);
          break;
        case "Item_9":
          _item_9 = new Item_11(sub);
          break;
        case "Item_10":
          _item_10 = new Item_11(sub);
          break;
        case "Item_12":
          _item_12 = new Item_11(sub);
          break;
        case "Item_13":
          _item_13 = new Item_11(sub);
          break;
        case "Item_14":
          _item_14 = new Item_11(sub);
          break;
        case "Item_15":
          _item_15 = new Item_11(sub);
          break;
        case "Item_16":
          _item_16 = new Item_11(sub);
          break;
        case "Item_17":
          _item_17 = new Item_11(sub);
          break;
        case "Item_18":
          _item_18 = new Item_11(sub);
          break;
        case "Item_19":
          _item_19 = new Item_11(sub);
          break;
        case "Item_20":
          _item_20 = new Item_11(sub);
          break;
        case "Item_21":
          _item_21 = new Item_11(sub);
          break;
        case "Item_22":
          _item_22 = new Item_11(sub);
          break;
        case "Item_23":
          _item_23 = new Item_11(sub);
          break;
        case "Item_24":
          _item_24 = new Item_11(sub);
          break;
        case "Item_25":
          _item_25 = new Item_11(sub);
          break;
        case "Item_26":
          _item_26 = new Item_11(sub);
          break;
        case "Item_27":
          _item_27 = new Item_11(sub);
          break;
        case "Item_28":
          _item_28 = new Item_11(sub);
          break;
        case "Item_29":
          _item_29 = new Item_11(sub);
          break;
        case "Item_30":
          _item_30 = new Item_11(sub);
          break;
        case "Item_31":
          _item_31 = new Item_11(sub);
          break;
        case "Item_32":
          _item_32 = new Item_11(sub);
          break;
        case "Item_33":
          _item_33 = new Item_11(sub);
          break;
        case "Item_34":
          _item_34 = new Item_11(sub);
          break;
        case "Item_35":
          _item_35 = new Item_11(sub);
          break;
        case "Item_36":
          _item_36 = new Item_11(sub);
          break;
        case "Item_37":
          _item_37 = new Item_11(sub);
          break;
        case "Item_38":
          _item_38 = new Item_11(sub);
          break;
        case "Item_39":
          _item_39 = new Item_11(sub);
          break;
        case "Item_40":
          _item_40 = new Item_11(sub);
          break;
        case "Item_41":
          _item_41 = new Item_11(sub);
          break;
        case "Item_42":
          _item_42 = new Item_11(sub);
          break;
        case "Item_43":
          _item_43 = new Item_11(sub);
          break;
        case "Item_44":
          _item_44 = new Item_11(sub);
          break;
        case "Item_45":
          _item_45 = new Item_11(sub);
          break;
        case "Item_46":
          _item_46 = new Item_11(sub);
          break;
        case "Item_47":
          _item_47 = new Item_11(sub);
          break;
        case "Item_48":
          _item_48 = new Item_11(sub);
          break;
        case "Item_49":
          _item_49 = new Item_11(sub);
          break;
        case "Item_50":
          _item_50 = new Item_11(sub);
          break;
        case "Item_51":
          _item_51 = new Item_11(sub);
          break;
        case "Item_52":
          _item_52 = new Item_11(sub);
          break;
        case "Item_53":
          _item_53 = new Item_11(sub);
          break;
        case "Item_54":
          _item_54 = new Item_11(sub);
          break;
        case "Item_55":
          _item_55 = new Item_11(sub);
          break;
        case "Item_56":
          _item_56 = new Item_11(sub);
          break;
        case "Item_57":
          _item_57 = new Item_11(sub);
          break;
        case "Item_58":
          _item_58 = new Item_11(sub);
          break;
        case "Item_59":
          _item_59 = new Item_11(sub);
          break;
        case "Item_60":
          _item_60 = new Item_11(sub);
          break;
        case "Item_61":
          _item_61 = new Item_11(sub);
          break;
        case "Item_62":
          _item_62 = new Item_11(sub);
          break;
        case "Item_63":
          _item_63 = new Item_11(sub);
          break;
        case "Item_64":
          _item_64 = new Item_11(sub);
          break;
        case "Item_65":
          _item_65 = new Item_11(sub);
          break;
        case "Item_66":
          _item_66 = new Item_11(sub);
          break;
        case "Item_67":
          _item_67 = new Item_11(sub);
          break;
        case "Item_68":
          _item_68 = new Item_11(sub);
          break;
        case "Item_69":
          _item_69 = new Item_11(sub);
          break;
        case "Item_70":
          _item_70 = new Item_11(sub);
          break;
        case "Item_71":
          _item_71 = new Item_11(sub);
          break;
        case "Item_72":
          _item_72 = new Item_11(sub);
          break;
        case "Item_73":
          _item_73 = new Item_11(sub);
          break;
        case "Item_74":
          _item_74 = new Item_11(sub);
          break;
          default:
            if (sub.Name.Substring(0,6).Equals("Item_1"))
            {
              _item_1s.Add(new Item_11(sub));
              break;
            }
            _unMappedSections.Add(sub.Name);
          break;
        }
      }
    }

    public Item_11 Item_2
    {
     get { return _item_2; }
    }

    public Item_11 Item_3
    {
     get { return _item_3; }
    }

    public Item_11 Item_4
    {
     get { return _item_4; }
    }

    public Item_11 Item_5
    {
     get { return _item_5; }
    }

    public Item_11 Item_6
    {
     get { return _item_6; }
    }

    public Item_11 Item_7
    {
     get { return _item_7; }
    }

    public Item_11 Item_8
    {
     get { return _item_8; }
    }

    public Item_11 Item_9
    {
     get { return _item_9; }
    }

    public Item_11 Item_10
    {
     get { return _item_10; }
    }

    public Item_11 Item_12
    {
     get { return _item_12; }
    }

    public Item_11 Item_13
    {
     get { return _item_13; }
    }

    public Item_11 Item_14
    {
     get { return _item_14; }
    }

    public Item_11 Item_15
    {
     get { return _item_15; }
    }

    public Item_11 Item_16
    {
     get { return _item_16; }
    }

    public Item_11 Item_17
    {
     get { return _item_17; }
    }

    public Item_11 Item_18
    {
     get { return _item_18; }
    }

    public Item_11 Item_19
    {
     get { return _item_19; }
    }

    public Item_11 Item_20
    {
     get { return _item_20; }
    }

    public Item_11 Item_21
    {
     get { return _item_21; }
    }

    public Item_11 Item_22
    {
     get { return _item_22; }
    }

    public Item_11 Item_23
    {
     get { return _item_23; }
    }

    public Item_11 Item_24
    {
     get { return _item_24; }
    }

    public Item_11 Item_25
    {
     get { return _item_25; }
    }

    public Item_11 Item_26
    {
     get { return _item_26; }
    }

    public Item_11 Item_27
    {
     get { return _item_27; }
    }

    public Item_11 Item_28
    {
     get { return _item_28; }
    }

    public Item_11 Item_29
    {
     get { return _item_29; }
    }

    public Item_11 Item_30
    {
     get { return _item_30; }
    }

    public Item_11 Item_31
    {
     get { return _item_31; }
    }

    public Item_11 Item_32
    {
     get { return _item_32; }
    }

    public Item_11 Item_33
    {
     get { return _item_33; }
    }

    public Item_11 Item_34
    {
     get { return _item_34; }
    }

    public Item_11 Item_35
    {
     get { return _item_35; }
    }

    public Item_11 Item_36
    {
     get { return _item_36; }
    }

    public Item_11 Item_37
    {
     get { return _item_37; }
    }

    public Item_11 Item_38
    {
     get { return _item_38; }
    }

    public Item_11 Item_39
    {
     get { return _item_39; }
    }

    public Item_11 Item_40
    {
     get { return _item_40; }
    }

    public Item_11 Item_41
    {
     get { return _item_41; }
    }

    public Item_11 Item_42
    {
     get { return _item_42; }
    }

    public Item_11 Item_43
    {
     get { return _item_43; }
    }

    public Item_11 Item_44
    {
     get { return _item_44; }
    }

    public Item_11 Item_45
    {
     get { return _item_45; }
    }

    public Item_11 Item_46
    {
     get { return _item_46; }
    }

    public Item_11 Item_47
    {
     get { return _item_47; }
    }

    public Item_11 Item_48
    {
     get { return _item_48; }
    }

    public Item_11 Item_49
    {
     get { return _item_49; }
    }

    public Item_11 Item_50
    {
     get { return _item_50; }
    }

    public Item_11 Item_51
    {
     get { return _item_51; }
    }

    public Item_11 Item_52
    {
     get { return _item_52; }
    }

    public Item_11 Item_53
    {
     get { return _item_53; }
    }

    public Item_11 Item_54
    {
     get { return _item_54; }
    }

    public Item_11 Item_55
    {
     get { return _item_55; }
    }

    public Item_11 Item_56
    {
     get { return _item_56; }
    }

    public Item_11 Item_57
    {
     get { return _item_57; }
    }

    public Item_11 Item_58
    {
     get { return _item_58; }
    }

    public Item_11 Item_59
    {
     get { return _item_59; }
    }

    public Item_11 Item_60
    {
     get { return _item_60; }
    }

    public Item_11 Item_61
    {
     get { return _item_61; }
    }

    public Item_11 Item_62
    {
     get { return _item_62; }
    }

    public Item_11 Item_63
    {
     get { return _item_63; }
    }

    public Item_11 Item_64
    {
     get { return _item_64; }
    }

    public Item_11 Item_65
    {
     get { return _item_65; }
    }

    public Item_11 Item_66
    {
     get { return _item_66; }
    }

    public Item_11 Item_67
    {
     get { return _item_67; }
    }

    public Item_11 Item_68
    {
     get { return _item_68; }
    }

    public Item_11 Item_69
    {
     get { return _item_69; }
    }

    public Item_11 Item_70
    {
     get { return _item_70; }
    }

    public Item_11 Item_71
    {
     get { return _item_71; }
    }

    public Item_11 Item_72
    {
     get { return _item_72; }
    }

    public Item_11 Item_73
    {
     get { return _item_73; }
    }

    public Item_11 Item_74
    {
     get { return _item_74; }
    }

    public List<Item_11> Item_1s
   {
     get { return _item_1s; }
    }

    public int Touched
    {
      get
      {
        return _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("Touched", 1).GetParameter(1).Value = value;
      }
    }

    public int IsDataUsedInSetup
    {
      get
      {
        return _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("IsDataUsedInSetup", 1).GetParameter(1).Value = value;
      }
    }

    public int MzSEPfsListItemCount
    {
      get
      {
        return _pfsHandle.GetKeyword("MzSEPfsListItemCount", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MzSEPfsListItemCount", 1).GetParameter(1).Value = value;
      }
    }

    public int NumberOfItems
    {
      get
      {
        return _pfsHandle.GetKeyword("NumberOfItems", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("NumberOfItems", 1).GetParameter(1).Value = value;
      }
    }

    public int MinimumOutputTimestep
    {
      get
      {
        return _pfsHandle.GetKeyword("MinimumOutputTimestep", 1).GetParameter(1).ToInt();
      }
      set
      {
        _pfsHandle.GetKeyword("MinimumOutputTimestep", 1).GetParameter(1).Value = value;
      }
    }

  }
}
